steps:
  - name: 'node:12'
    entrypoint: npm
    args: ['install']
  - name: 'node:12'
    entrypoint: npm
    args: ['test']
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-f", "Dockerfile", "-t", "gcr.io/$PROJECT_ID/ethstats:$COMMIT_SHA", "."]
    waitFor: ["-"]
timeout: 1200s
images:
  - "gcr.io/$PROJECT_ID/ethstats:$COMMIT_SHA"
